# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/osher/Verilog_Projects/AXIS_GAUSSIAN_IP2/AXIS_GAUSSIAN_IP2.srcs/sources_1/ip/OutputBuffer/OutputBuffer.xci
# IP: The module: 'OutputBuffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/osher/Verilog_Projects/AXIS_GAUSSIAN_IP2/AXIS_GAUSSIAN_IP2.srcs/sources_1/ip/OutputBuffer/OutputBuffer.xdc
# XDC: The top module name and the constraint reference have the same name: 'OutputBuffer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/osher/Verilog_Projects/AXIS_GAUSSIAN_IP2/AXIS_GAUSSIAN_IP2.srcs/sources_1/ip/OutputBuffer/OutputBuffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'OutputBuffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/osher/Verilog_Projects/AXIS_GAUSSIAN_IP2/AXIS_GAUSSIAN_IP2.srcs/sources_1/ip/OutputBuffer/OutputBuffer.xci
# IP: The module: 'OutputBuffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/osher/Verilog_Projects/AXIS_GAUSSIAN_IP2/AXIS_GAUSSIAN_IP2.srcs/sources_1/ip/OutputBuffer/OutputBuffer.xdc
# XDC: The top module name and the constraint reference have the same name: 'OutputBuffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/osher/Verilog_Projects/AXIS_GAUSSIAN_IP2/AXIS_GAUSSIAN_IP2.srcs/sources_1/ip/OutputBuffer/OutputBuffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'OutputBuffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
